name: Release

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: gh release list"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # gh release edit v1.0.0 --prerelease=false
