name: Release
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select Update Version
        options:
          - patch
          - minor
          - major
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish release
        run: |
          gh release view
          echo "choice is ${{ github.event.inputs.choice }} / ${{ inputs.choice }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Publish:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/github-script@v6
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat
        with:
          script: |
            console.log(${{ inputs.choice }} selected!!!)
      # - name: Update Package.json Version
      #   id: update
      #   uses: './../.github/workflows/package/versionUpdate'
      #   with:
      #     semVer: 1.0.0
      # - name: Echo Updated Version
      #   run: |
      #     echo "${{ steps.update.outputs.result }}"
