name: Release
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select Update Version
        options:
          - patch
          - minor
          - major
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/checkout@v2
      - name: Upload Iamge to ECR
        run: |
          chmod +x ./deployment/nginx/deploy.sh
          ./deployment/nginx/deploy.sh
        shell: bash
  Publish:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          SEM_VER: ${{ inputs.choice }}
        with:
          script: |
            const { SEM_VER } = process.env
            const script = require("./.github/workflows/getNextVersion.js")
            console.log(script({github, context, versionType: SEM_VER}))
            gh release edit "$script" --draft=false
